nodes:
  - name: agent_orchestrator
    module: "app.agent.agents.agent_orchestrator.AgentOrchestrator"
    description: "Orchestrate the tasks"

  - name: agent_intake
    module: "app.agent.agents.agent_intake.AgentIntake"
    description: "Extract information from request"

  - name: agent_disaster
    module: "app.agent.agents.agent_disaster.AgentDisaster"
    description: "Handle disaster assignment or creation"
  
  - name: agent_task
    module: "app.agent.agents.agent_task.AgentTask"
    description: "Handle task creation"

  - name: agent_allocation
    module: "app.agent.agents.agent_allocation.AgentAllocation"
    description: "Handle resource and manpower allocation to tasks"

edges:
  - type: direct
    from: start
    to: agent_orchestrator

  - type: conditional
    from: agent_orchestrator
    route: app.agent.routes.route_orchestrator.RouteOrchestrator
    to:
      agent_intake: agent_intake
      agent_disaster: agent_disaster
      agent_task: agent_task
      agent_allocation: agent_allocation
      END: __end__

  - type: conditional
    from: agent_intake
    route: app.agent.routes.route_intake.RouteIntake
    to:
      agent_disaster: agent_disaster
      agent_task: agent_task
      END: __end__
  
  - type: conditional
    from: agent_disaster
    route: app.agent.routes.route_disaster.RouteDisaster
    to:
      agent_task: agent_task
      END: __end__

default_agent: agent_orchestrator