groq:
  PARSE_TEXT: "llama-3.3-70b-versatile"
  ANALYSE_IMAGE: "meta-llama/llama-4-scout-17b-16e-instruct"
  DISASTER_ASSIGNMENT: "llama-3.3-70b-versatile"
  DISASTER_CREATION: "llama-3.3-70b-versatile"
  TASK_CREATION: "llama-3.3-70b-versatile"
  DEFAULT: "llama-3.3-70b-versatile"  # Example of another task